apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: razor-application
  name: razor-application
  namespace: razor-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: razor-application
  template:
    metadata:
      labels:
        app: razor-application
    spec:
      containers:
        - image: bastion.okd4.guru.com:8443/dotnet/razor-application:latest
          imagePullPolicy: Always
          name: razor-application
          ports:
            - containerPort: 8080
              protocol: TCP